### ISSUE TITLE
get_best_lr - argmax

### ISSUE THREAD

**Issue by janthmueller** [surmenok/keras_lr_finder#32]
Why do you use the argmax method within get_best_lr? Since we are interested in the fastest decrease in the loss shouldn't we use argmin?

**Comment by JonnoFTW** [comment]
It does use `argmin`:

https://github.com/surmenok/keras_lr_finder/blob/3c8fe719d7e3291a1f72ff8a9a1c51e9fc5d520b/keras_lr_finder/lr_finder.py#L146-L149

**Comment by janthmueller** [comment]
Thank you, there seems to be an error on my end with my last pull with vs code.
